language: c

compiler:
    - clang
    - gcc

sudo: required

before_install:
    - git clone git://git.cryptomilk.org/projects/cmocka.git
    - cd cmocka && mkdir build && cd build
    - cmake .. && make -j2 && sudo make install

script:
    make && make test
