MAKEFLAGS += --no-print-directory

all: mysh

mysh: FORCE_MAKE
	
# FORCE_MAKE ensures that Makefile generated by the cmake is always run.
# As a PHONY target it has no associated file and thus its recipe
# is must be executed.
FORCE_MAKE: build/Makefile
	cd build && make

build/Makefile:
	mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..

.PHONY: clean FORCE

clean:
	rm -r build/
	rm mysh
